# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: terraform-aws-named-subnets
  description: 'DEPRECATED (use cloudposse/terraform-aws-dynamic-subnets instead): Terraform module for named subnets provisioning.'
  homepage: https://cloudposse.com/accelerate
  topics: terraform-module, availability-zone, subnet, aws, vpc, cidr, calculator, dynamic, hcl2

